name: Release

on:
  push:
    tags:
      # x.y.z version format
      - "[0-9]+.[0-9]+.[0-9]+*"

permissions:
  contents: write

jobs:
  create-release:
    if: github.repository_owner == 'devmatteini'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          persist-credentials: false

      - name: Get the release version from the tag
        run: |
          echo "NOTED_VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Print release version
        run: |
          echo "Version is: $NOTED_VERSION"

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./scripts/create-github-release.sh "$NOTED_VERSION"

  build:
    needs: [ create-release ]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          persist-credentials: false

      - name: Set up Java
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # 5.3.0
        with:
          distribution: temurin
          java-version: 24.0.2

      - name: Get the release version from the tag
        run: |
          echo "NOTED_VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Print release version
        run: |
          echo "Version is: $NOTED_VERSION"

      - name: Build release APK
        id: build_apk
        env:
          NOTED_KEYSTORE_ENCODED: ${{ secrets.NOTED_KEYSTORE_ENCODED }}
          NOTED_KEYSTORE_PASSWORD: ${{ secrets.NOTED_KEYSTORE_PASSWORD }}
          NOTED_KEY_ALIAS: ${{ vars.NOTED_KEY_ALIAS }}
          NOTED_KEY_PASSWORD: ${{ secrets.NOTED_KEY_PASSWORD }}
        run: |
          asset=$(./scripts/build-release-apk.sh "$NOTED_VERSION")
          echo "APK=$asset" >> $GITHUB_OUTPUT

      - name: Upload assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./scripts/upload-github-release-assets.sh \
              "$NOTED_VERSION" \
              ${{ steps.build_apk.outputs.APK }}

      - name: Delete keystore file
        if: always()
        run: rm -f noted-keystore.jks
